version: "3.3"
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8081:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    # volumes:
    #   - ./swagger/openapi.yaml:/openapi.yaml
    #   - ./swagger/openapi.yaml:/usr/share/nginx/html/api/openapi.yaml
    #もしかしたらvolume経由でも変更が反映されるかも
    environment:
      API_URL: http://localhost:8085/api/openapi.yaml
      # SWAGGER_JSON: "/openapi.yaml"
    depends_on:
      - file-nginx 
    networks:
      - swagger_link

  swagger-api:
    image: danielgtaylor/apisprout
    container_name: "swagger-api"
    depends_on:
      - swagger-ui
    ports:
      - "8083:8000"
    volumes:
      - ./swagger/openapi.yaml:/openapi.yaml
    command: /openapi.yaml --watch
    networks:
      swagger_link:
        aliases:
          - local.swagger.apisprout

  swagger-nginx:
    image: nginx:mainline-alpine
    container_name: "swagger-nginx"
    ports:
      - "8084:8084"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - swagger-api
    networks:
      swagger_link:
        aliases:
          - local.swagger.api

  file-nginx:
    image: nginx:1.17
    container_name: "file-nginx"
    ports:
      - "8085:80"
    privileged: true
    volumes:
      - ./swagger/:/usr/share/nginx/html/api/
      - ./nginx/file-server.conf:/etc/nginx/conf.d/default.conf
    networks:
      swagger_link:
        aliases:
          - local.swagger.file
networks:
  swagger_link:
    external: true
